#!/usr/bin/env bash

# Test version of Dynamic iOS Workflow Script
# Sets default environment variables for testing

# Set default environment variables for testing
export BUNDLE_ID="com.test.app"
export APP_NAME="Test App"
export VERSION_NAME="1.0.0"
export VERSION_CODE="1"
export APPLE_TEAM_ID="TEST123"
export CERT_PASSWORD="testpass"
export PROFILE_URL="https://example.com/profile.mobileprovision"
export PROJECT_ID="test-project-id"
export APP_ID="12345"
export ORG_NAME="Test Organization"
export WEB_URL="https://test.com"
export USER_NAME="testuser"
export EMAIL_ID="test@example.com"
export BRANCH="main"
export WORKFLOW_ID="ios-workflow"
export PKG_NAME="com.test.app"
export PUSH_NOTIFY="false"
export IS_CHATBOT="false"
export IS_DOMAIN_URL="false"
export IS_SPLASH="true"
export IS_PULLDOWN="true"
export IS_BOTTOMMENU="true"
export IS_LOAD_IND="true"
export IS_CAMERA="false"
export IS_LOCATION="false"
export IS_MIC="false"
export IS_NOTIFICATION="false"
export IS_CONTACT="false"
export IS_BIOMETRIC="false"
export IS_CALENDAR="false"
export IS_STORAGE="false"
export IS_GOOGLE_AUTH="false"
export IS_APPLE_AUTH="false"
export LOGO_URL=""
export SPLASH_URL=""
export SPLASH_BG_URL=""
export SPLASH_BG_COLOR="#FFFFFF"
export SPLASH_TAGLINE=""
export SPLASH_TAGLINE_COLOR="#000000"
export SPLASH_TAGLINE_FONT="Roboto"
export SPLASH_TAGLINE_SIZE="16"
export SPLASH_TAGLINE_BOLD="false"
export SPLASH_TAGLINE_ITALIC="false"
export SPLASH_ANIMATION="none"
export SPLASH_DURATION="3"
export BOTTOMMENU_ITEMS="[]"
export BOTTOMMENU_BG_COLOR="#FFFFFF"
export BOTTOMMENU_ICON_COLOR="#000000"
export BOTTOMMENU_TEXT_COLOR="#000000"
export BOTTOMMENU_FONT="DM Sans"
export BOTTOMMENU_FONT_SIZE="14"
export BOTTOMMENU_FONT_BOLD="false"
export BOTTOMMENU_FONT_ITALIC="false"
export BOTTOMMENU_ACTIVE_TAB_COLOR="#0000FF"
export BOTTOMMENU_ICON_POSITION="top"
export BOTTOMMENU_VISIBLE_ON=""
export FIREBASE_CONFIG_ANDROID=""
export FIREBASE_CONFIG_IOS=""
export KEY_STORE_URL=""
export CM_KEYSTORE_PASSWORD=""
export CM_KEY_ALIAS=""
export CM_KEY_PASSWORD=""
export APNS_KEY_ID=""
export APNS_AUTH_KEY_URL=""
export CERT_P12_URL=""
export CERT_CER_URL=""
export CERT_KEY_URL=""
export PROFILE_TYPE="app-store"
export APP_STORE_CONNECT_KEY_IDENTIFIER=""
export ENABLE_EMAIL_NOTIFICATIONS="false"
export EMAIL_SMTP_SERVER=""
export EMAIL_SMTP_PORT="587"
export EMAIL_SMTP_USER=""
export EMAIL_SMTP_PASS=""
export BUILD_ID="test-build"
export BUILD_DIR=""
export PROJECT_ROOT=""
export OUTPUT_DIR="output"
export GRADLE_OPTS=""
export XCODE_PARALLEL_JOBS="4"
export FLUTTER_BUILD_ARGS=""

# Call the main dynamic workflow script
bash lib/scripts/ios-workflow/dynamic_ios_workflow.sh 