name: untitled
description: "A new Flutter project."
publish_to: "none"
version: 1.0.7+43

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  flutter_local_notifications: ^17.1.2
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.3
  speech_to_text: ^7.0.0
  html: ^0.15.4
  flutter_inappwebview: ^6.0.0
  permission_handler: ^11.3.0
  package_info_plus: ^8.3.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  http: ^1.2.1
  google_sign_in: ^6.2.1
  # sign_in_with_apple: ^6.0.0  # Uncomment when IS_APPLE_AUTH=true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/
