// GENERATED FILE: DO NOT EDIT
//
// This file is generated by lib/scripts/utils/gen_env_config.sh
// It contains all environment-specific variables for the app.

class EnvConfig {
  // App Metadata
  static const String projectId = "local-dev-project";
  static const String appId = "1000";
  static const String versionName = "1.0.0";
  static const int versionCode = 1;
  static const String appName = "QuikApp";
  static const String orgName = "QuikApp";
  static const String webUrl = "https://pixaware.co";
  static const String userName = "developer";
  static const String emailId = "dev@quikapp.co";
  static const String branch = "main";
  static const String workflowId = "local-dev";

  // Package Identifiers
  static const String pkgName = "com.quikapp.app";
  static const String bundleId =
      ""; // Bundle ID not available for Android-only builds

  // Feature Flags (converted to bool)
  static const bool pushNotify = false;
  static const bool isChatbot = true;
  static const bool isDomainUrl = true;
  static const bool isSplash = true;
  static const bool isPulldown = true;
  static const bool isBottommenu = true;
  static const bool isLoadIndicator = true;

  // Permissions (converted to bool)
  static const bool isCamera = false;
  static const bool isLocation = false;
  static const bool isMic = true;
  static const bool isNotification = true;
  static const bool isContact = false;
  static const bool isBiometric = false;
  static const bool isCalendar = false;
  static const bool isStorage = false;

  // OAuth Authentication
  static const bool isGoogleAuth = true;
  static const bool isAppleAuth = false;

  // UI/Branding
  static const String logoUrl = "";
  static const String splashUrl = "";
  static const String splashBg = "";
  static const String splashBgColor = "#FFFFFF";
  static const String splashTagline = "PixAware";
  static const String splashTaglineColor = "#000000";
  static const String splashTaglineFont = "Roboto";
  static const String splashTaglineSize = "20";
  static const bool splashTaglineBold = false;
  static const bool splashTaglineItalic = false;
  static const String splashAnimation = "fade";
  static const int splashDuration = 3;

  // Bottom Menu Configuration
  static const String bottommenuItems = """[
    {
      "label": "Home",
      "icon": {
        "type": "preset",
        "name": "home_outlined"
      },
      "url": "https://pixaware.co/"
    },
    {
      "label": "Solutions",
      "icon": {
        "type": "preset",
        "name": "build"
      },
      "url": "https://pixaware.co/solutions/"
    },
    {
      "label": "About",
      "icon": {
        "type": "preset",
        "name": "info"
      },
      "url": "https://pixaware.co/who-we-are/"
    },
    {
      "label": "Contact",
      "icon": {
        "type": "preset",
        "name": "phone"
      },
      "url": "https://pixaware.co/lets-talk/"
    }
  ]""";
  static const String bottommenuBgColor = "#FFFFFF";
  static const String bottommenuIconColor = "#000000";
  static const String bottommenuTextColor = "#000000";
  static const String bottommenuFont = "Roboto";
  static const double bottommenuFontSize = 12;
  static const bool bottommenuFontBold = false;
  static const bool bottommenuFontItalic = false;
  static const String bottommenuActiveTabColor = "#000000";
  static const String bottommenuIconPosition = "above";
  static const String bottommenuVisibleOn = "all";

  // Firebase Configuration
  static const String firebaseConfigAndroid = "";
  static const String firebaseConfigIos = "";

  // Android Signing
  static const String keyStoreUrl = "";
  static const String cmKeystorePassword = "";
  static const String cmKeyAlias = "";
  static const String cmKeyPassword = "";

  // Email Configuration
  static const bool enableEmailNotifications = false;
  static const String emailSmtpServer = "";
  static const int emailSmtpPort = 0;
  static const String emailSmtpUser = "";
  static const String emailSmtpPass = "";

  // Build Environment
  static const String buildId = "";
  static const String buildDir = "";
  static const String projectRoot = "";
  static const String outputDir = "";

  // Memory and Performance Settings
  static const String gradleOpts = "";
  static const int xcodeParallelJobs = 0;
  static const String flutterBuildArgs = "";

  // Utility Methods
  static bool get isAndroidBuild => workflowId.startsWith('android');
  static bool get isIosBuild => workflowId.contains('ios');
  static bool get isCombinedBuild => workflowId == 'combined';
  static bool get hasFirebase =>
      firebaseConfigAndroid.isNotEmpty || firebaseConfigIos.isNotEmpty;
  static bool get hasKeystore => keyStoreUrl.isNotEmpty;
  static bool get hasIosSigning =>
      false; // iOS signing not available for Android-only builds
}
