#!/bin/bash
set -euo pipefail

# Debug script to check environment variables
echo "🔍 ===== ENVIRONMENT VARIABLES DEBUG ====="
echo "📊 CM_BUILD_ID: ${CM_BUILD_ID:-not set}"
echo "📊 CM_PROJECT_ID: ${CM_PROJECT_ID:-not set}"
echo "📊 PROJECT_ID: ${PROJECT_ID:-not set}"
echo "📊 APP_ID: ${APP_ID:-not set}"
echo "📊 APP_NAME: ${APP_NAME:-not set}"
echo "📊 PKG_NAME: ${PKG_NAME:-not set}"
echo "📊 VERSION_NAME: ${VERSION_NAME:-not set}"
echo "📊 VERSION_CODE: ${VERSION_CODE:-not set}"
echo "📊 ORG_NAME: ${ORG_NAME:-not set}"
echo "📊 WEB_URL: ${WEB_URL:-not set}"
echo "📊 USER_NAME: ${USER_NAME:-not set}"
echo "📊 EMAIL_ID: ${EMAIL_ID:-not set}"
echo "📊 WORKFLOW_ID: ${WORKFLOW_ID:-not set}"
echo "📊 BUNDLE_ID: ${BUNDLE_ID:-not set}"
echo "📊 LOGO_URL: ${LOGO_URL:-not set}"
echo "📊 SPLASH_URL: ${SPLASH_URL:-not set}"
echo "📊 FIREBASE_CONFIG_ANDROID: ${FIREBASE_CONFIG_ANDROID:-not set}"
echo "📊 KEY_STORE_URL: ${KEY_STORE_URL:-not set}"
echo "📊 PUSH_NOTIFY: ${PUSH_NOTIFY:-not set}"
echo "📊 IS_CHATBOT: ${IS_CHATBOT:-not set}"
echo "📊 IS_DOMAIN_URL: ${IS_DOMAIN_URL:-not set}"
echo "📊 IS_SPLASH: ${IS_SPLASH:-not set}"
echo "📊 IS_PULLDOWN: ${IS_PULLDOWN:-not set}"
echo "📊 IS_BOTTOMMENU: ${IS_BOTTOMMENU:-not set}"
echo "📊 IS_LOAD_IND: ${IS_LOAD_IND:-not set}"
echo "📊 IS_CAMERA: ${IS_CAMERA:-not set}"
echo "📊 IS_LOCATION: ${IS_LOCATION:-not set}"
echo "📊 IS_MIC: ${IS_MIC:-not set}"
echo "📊 IS_NOTIFICATION: ${IS_NOTIFICATION:-not set}"
echo "📊 IS_CONTACT: ${IS_CONTACT:-not set}"
echo "📊 IS_BIOMETRIC: ${IS_BIOMETRIC:-not set}"
echo "📊 IS_CALENDAR: ${IS_CALENDAR:-not set}"
echo "📊 IS_STORAGE: ${IS_STORAGE:-not set}"
echo "📊 BOTTOMMENU_ITEMS: ${BOTTOMMENU_ITEMS:-not set}"
echo "📊 BOTTOMMENU_BG_COLOR: ${BOTTOMMENU_BG_COLOR:-not set}"
echo "📊 BOTTOMMENU_ICON_COLOR: ${BOTTOMMENU_ICON_COLOR:-not set}"
echo "📊 BOTTOMMENU_TEXT_COLOR: ${BOTTOMMENU_TEXT_COLOR:-not set}"
echo "📊 BOTTOMMENU_FONT: ${BOTTOMMENU_FONT:-not set}"
echo "📊 BOTTOMMENU_FONT_SIZE: ${BOTTOMMENU_FONT_SIZE:-not set}"
echo "📊 BOTTOMMENU_FONT_BOLD: ${BOTTOMMENU_FONT_BOLD:-not set}"
echo "📊 BOTTOMMENU_FONT_ITALIC: ${BOTTOMMENU_FONT_ITALIC:-not set}"
echo "📊 BOTTOMMENU_ACTIVE_TAB_COLOR: ${BOTTOMMENU_ACTIVE_TAB_COLOR:-not set}"
echo "📊 BOTTOMMENU_ICON_POSITION: ${BOTTOMMENU_ICON_POSITION:-not set}"
echo "📊 CM_KEYSTORE_PASSWORD: ${CM_KEYSTORE_PASSWORD:-not set}"
echo "📊 CM_KEY_ALIAS: ${CM_KEY_ALIAS:-not set}"
echo "📊 CM_KEY_PASSWORD: ${CM_KEY_PASSWORD:-not set}"
echo "📊 ENABLE_EMAIL_NOTIFICATIONS: ${ENABLE_EMAIL_NOTIFICATIONS:-not set}"
echo "📊 EMAIL_SMTP_SERVER: ${EMAIL_SMTP_SERVER:-not set}"
echo "📊 EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-not set}"
echo "📊 EMAIL_SMTP_USER: ${EMAIL_SMTP_USER:-not set}"
echo "📊 EMAIL_SMTP_PASS: ${EMAIL_SMTP_PASS:+SET}"
echo "🔍 ===== END ENVIRONMENT VARIABLES DEBUG =====" 